### ISSUE TITLE
Timeout in dockerbridge

### ISSUE THREAD

**Issue by daniel86** [knowrob/docker#143]
Randomly happens on login. A minute is a lot in this case, lowering timeout to 10secs for now

    ERROR:root:JsonRpcError(-32603): UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60) -- Traceback (most recent call last):

    File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
      result = rpc_function(*positional_params, **named_params)
    File "dockerbridge.py", line 155, in files_writesecret
      filemanager.tocontainer(container, data, '/etc/rosauth/secret')
    File "/opt/dockerbridge/filemanager.py", line 71, in tocontainer
      self.__writefile(container, source, targetfile, user)
    File "/opt/dockerbridge/filemanager.py", line 210, in __writefile
      self.__stop_and_remove(cont, True)
    File "/opt/dockerbridge/filemanager.py", line 248, in __stop_and_remove
      self.docker.wait(container, timeout=60)

**Comment by daniel86** [comment]
@mh0rst any idea what goes wrong here?

**Comment by daniel86** [comment]
behaviour is much better with timeout=10sec

**Comment by mh0rst** [comment]
How often does this occur and since when? I don't remember having timeout issues when I implemented this.
What docker version are you currently using?

**Comment by daniel86** [comment]
Could be related to recent local docker update to version `1.12.4`.
On my laptop, it happens in about 33% of the log-ins.

Is the `docker.wait` call waiting for the intermediate container to be started?
It should be there within seconds or am I wrong?
